type: task_block
title: Save Disaster
description: Save Disaster to CSV
icon: https://static.oomol.com/icons/python.png
executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: disaster
    json_schema:
      contentMediaType: oomol/var
  - handle: dir
    json_schema:
      type: string
      ui:widget: dir
  - handle: name
    json_schema:
      type: string
