type: task_block
title: Classify Data
icon: https://static.oomol.com/icons/python.png
executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: climate_data
  - handle: weekly_stats
  - handle: sigma1
    json_schema:
      type: integer
    value: 3
  - handle: sigma2
    json_schema:
      type: integer
    value: 2
  - handle: year_from
    json_schema:
      type: integer
    value: 2010
  - handle: year_to
    json_schema:
      type: integer
    value: 2020
  - handle: indicator
    json_schema:
      type: string
  - handle: levels
    json_schema:
      type: array
      items:
        type: string
outputs_def:
  - handle: disaster
