type: task_block
title: Read Dataframe
icon: https://static.oomol.com/icons/python.png
executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: csv
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: dataframe
