type: task_block
title: Read Dataframe
icon: ":fa6-solid:file-import:currentColor:"
executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: csv
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: dataframe
    json_schema:
      contentMediaType: oomol/var
